# NPTEL Week 4 – R Programming: Conceptual Examples

This Colab notebook is based on the uploaded **FRS Lecture Notes Week 04**.

**Goal:** practice the important concepts and operators from Week 4 without repeating trivial one-line questions.

Topics covered:
- Matrix construction and indexing
- Row/column names
- Diagonal matrices and transpose
- Row/column sums and means
- Scalar arithmetic on matrices
- Matrix addition/subtraction
- Matrix multiplication `%*%`
- `crossprod()`, inverse and eigen values/vectors
- Relational operators: `>`, `>=`, `<`, `<=`, `==`, `!=`
- Logical operators: `!`, `&`, `&&`, `|`, `||`
- `xor()`, `isTRUE()`, `isFALSE()`
- Logical indexing with conditions

## 1. Matrix creation, `byrow` and indexing

The important idea is that R fills a matrix column-wise by default. Using `byrow = TRUE` changes this behavior.

In [ ]:
# Create the same data in two different layouts
x_col <- matrix(1:12, nrow = 4, ncol = 3)
x_row <- matrix(1:12, nrow = 4, ncol = 3, byrow = TRUE)

x_col
x_row

# Access one row, one column and a submatrix
x_row[3, ]
x_row[, 2]
x_row[2:4, 1:2]

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12

[1] 7 8 9

[1]  2  5  8 11

     [,1] [,2]
[1,]  4    5
[2,]  7    8
[3,] 10   11

## 2. Row and column names

Use `rownames()` and `colnames()` to label matrix dimensions.

In [ ]:
x <- matrix(1:12, nrow = 4, ncol = 3)

rownames(x) <- paste0("r", 1:4)
colnames(x) <- paste0("c", 1:3)

x

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

## 3. Matrix indexing with selected rows and columns

This combines the `[]` indexing operator with `c()` to select non-consecutive rows/columns.

In [ ]:
x <- matrix(1:15, nrow = 5, ncol = 3, byrow = TRUE)

# Rows 1 and 4, columns 1 and 3
x[c(1, 4), c(1, 3)]

# Rows 4 and 5, columns 2 and 3
x[4:5, 2:3]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

     [,1] [,2]
[1,] 11   12
[2,] 14   15

## 4. Diagonal matrix and identity matrix

`diag()` can create an identity matrix or a diagonal matrix with a specified diagonal value.

In [ ]:
I3 <- diag(1, nrow = 3, ncol = 3)
D3 <- diag(5, nrow = 3, ncol = 3)

I3
D3

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

## 5. Transpose and row/column summaries

`t()` changes rows into columns. `rowSums()`, `colSums()`, `rowMeans()` and `colMeans()` summarize matrix dimensions.

In [ ]:
x <- matrix(1:8, nrow = 4, ncol = 2, byrow = TRUE)

x
t(x)

rowSums(x)
colSums(x)

rowMeans(x)
colMeans(x)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

[1]  3  7 11 15

[1] 16 20

[1] 1.5 3.5 5.5 7.5

[1] 4 5

## 6. Scalar arithmetic: `+`, `-`, `*`, `/`

A scalar operation is applied to every element of the matrix.

In [ ]:
x <- matrix(1:8, nrow = 4, ncol = 2, byrow = TRUE)

x + 5       # addition
x - 5       # subtraction
5 * x       # multiplication
x / 2       # division

## 7. Matrix addition and subtraction

For ordinary matrix `+` and `-`, the matrices must have compatible dimensions. The operation is element-wise.

In [ ]:
x <- matrix(1:8, nrow = 4, ncol = 2, byrow = TRUE)
y <- matrix(11:18, nrow = 4, ncol = 2, byrow = TRUE)

x + y
x - y

# A useful combined expression from the lecture idea
x + 4*x
4*x - x

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

## 8. `%*%` – true matrix multiplication

`%*%` is different from `*`. It performs matrix multiplication using rows of the first matrix and columns of the second.

In [ ]:
x <- matrix(1:8, nrow = 4, ncol = 2, byrow = TRUE)
y <- matrix(11:18, nrow = 2, ncol = 4, byrow = TRUE)

x %*% y
y %*% x

# Compare element-wise multiplication with matrix multiplication
a <- matrix(c(1, 2, 3, 4), nrow = 2, byrow = TRUE)
b <- matrix(c(5, 6, 7, 8), nrow = 2, byrow = TRUE)

a * b
a %*% b

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

     [,1] [,2]
[1,] 210  260
[2,] 274  340

     [,1] [,2]
[1,]  5   12
[2,] 21   32

     [,1] [,2]
[1,] 19   22
[2,] 43   50

## 9. Transpose multiplied by the original matrix

A common matrix calculation is X'X. In R this is written as `t(x) %*% x`.

In [ ]:
x <- matrix(1:8, nrow = 4, ncol = 2, byrow = TRUE)

xtx <- t(x) %*% x
xxt <- x %*% t(x)

xtx
xxt

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

## 10. `crossprod()` for X'X

The lecture uses `crossprod(x)` as a faster way to calculate `t(x) %*% x`.

In [ ]:
x <- matrix(1:8, nrow = 4, ncol = 2, byrow = TRUE)

t(x) %*% x
crossprod(x)

# They should give the same matrix
all(t(x) %*% x == crossprod(x))

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1] [,2]
[1,]  84  100
[2,] 100  120

[1] TRUE

## 11. Inverse using `solve()`

For an invertible square matrix, `solve()` can calculate the inverse.

In [ ]:
y <- matrix(c(84, 100,
              100, 120),
            nrow = 2, byrow = TRUE)

y_inv <- solve(y)
y_inv

# Check the inverse concept
y %*% y_inv

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

     [,1]         [,2]
[1,] 1.000000e+00 4.440892e-15
[2,] 7.105427e-15 1.000000e+00

## 12. Eigen values and eigen vectors

`eigen()` returns both eigen values and eigen vectors of a square matrix.

In [ ]:
y <- matrix(c(84, 100,
              100, 120),
            nrow = 2, byrow = TRUE)

eig <- eigen(y)

eig$values
eig$vectors

[1] 203.6070864   0.3929136

     [,1]      [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

# Relational and Logical Operators

The Week 4 notes cover `>`, `>=`, `<`, `<=`, `==`, `!=`, `!`, `&`, `&&`, `|`, `||`, `xor()`, `isTRUE()` and `isFALSE()`.

The following examples are deliberately grouped so that each example demonstrates a concept rather than merely testing one number.

## 13. Relational operators together

Relational operators produce logical values (`TRUE` or `FALSE`).

In [ ]:
marks <- c(45, 72, 81, 60, 39)

marks > 60
marks >= 60
marks < 60
marks <= 60
marks == 60
marks != 60

[1] FALSE  TRUE  TRUE FALSE FALSE

[1] FALSE  TRUE  TRUE  TRUE FALSE

[1]  TRUE FALSE FALSE FALSE  TRUE

[1]  TRUE FALSE FALSE  TRUE  TRUE

[1] FALSE FALSE FALSE  TRUE FALSE

[1]  TRUE  TRUE  TRUE FALSE  TRUE

## 14. Comparing two vectors element-by-element

Relational operators work element-wise on vectors.

In [ ]:
x <- c(1, 2, 3)
y <- c(4, 2, 1)

x > y
x < y
x == y
x != y

[1] FALSE FALSE  TRUE

[1]  TRUE FALSE FALSE

[1] FALSE  TRUE FALSE

[1]  TRUE FALSE  TRUE

## 15. Negation `!`

`!` reverses a logical result: `TRUE` becomes `FALSE` and vice versa.

In [ ]:
passed <- c(TRUE, FALSE, TRUE, FALSE)

passed
!passed

# Negating a condition
marks <- c(45, 72, 81, 60, 39)
marks > 60
!(marks > 60)

[1]  TRUE FALSE  TRUE FALSE

[1] FALSE  TRUE FALSE  TRUE

[1] FALSE  TRUE  TRUE FALSE FALSE

[1]  TRUE FALSE FALSE  TRUE  TRUE

## 16. Element-wise AND `&`

`&` evaluates the condition for every element of a vector.

In [ ]:
marks <- c(45, 72, 81, 60, 39)

eligible <- (marks >= 50) & (marks <= 80)

marks >= 50
marks <= 80
eligible

# Use the logical result to select values
marks[eligible]

[1] FALSE  TRUE  TRUE  TRUE FALSE

[1]  TRUE  TRUE FALSE  TRUE  TRUE

[1] FALSE  TRUE FALSE  TRUE FALSE

[1] 72 60

## 17. Element-wise OR `|`

`|` evaluates both conditions element-by-element.

In [ ]:
marks <- c(45, 72, 81, 60, 39)

special <- (marks < 50) | (marks > 80)

special
marks[special]

[1]  TRUE FALSE  TRUE FALSE  TRUE

[1] 45 81 39

## 18. Why `&` and `&&` are different

`&` works element-wise. `&&` examines only the first element of the operands.

This is one of the important conceptual distinctions in the Week 4 notes.

In [ ]:
x <- c(8, 18)

(x < 10) & (x > 2)
# The error happens because && expects single logical values.
# When (x < 10) evaluates to c(TRUE, FALSE), it's a vector of length 2.
# && tries to use this vector where a single logical is expected, leading to the 'length = 2' error.
# To use && correctly with vectors, you should explicitly select the first element.
(x[1] < 10) && (x[1] > 2)

# The first result contains one logical value for each element.
# The second result is based only on the first element.

[1]  TRUE FALSE

[1] TRUE

## 19. Why `|` and `||` are different

Similarly, `|` is element-wise while `||` evaluates only the first element.

In [ ]:
x <- c(8, 18)

(x < 10) | (x < 2)
# The error happens because || expects single logical values, similar to &&.
# When (x < 10) evaluates to c(TRUE, FALSE), it's a vector of length 2.
# || tries to use this vector where a single logical is expected, leading to the 'length = 2' error.
# To use || correctly with vectors, you should explicitly select the first element.
(x[1] < 10) || (x[1] < 2)

[1]  TRUE FALSE

[1] TRUE

## 20. Short-circuit behavior with `&&`

`&&` evaluates from left to right and stops once the final result is determined.

In [ ]:
x <- 1:6

# Only the first element of x is considered by &&
# The error happened because && expects single logical values, not vectors.
# (x > 2) evaluates to a vector of length 6, causing the 'length = 6' error.
# To use && correctly, you must explicitly refer to the first element.
(x[1] > 2) && (x[1] < 5)

# Equivalent first-element view
(x[1] > 2) & (x[1] < 5)

[1] FALSE

[1] FALSE

## 21. Combining relational and logical operators for filtering

This is a practical example of using several operators together.

In [ ]:
x <- 1:10

# Values greater than 2 AND less than 8
x[(x > 2) & (x < 8)]

# Values less than 3 OR greater than 8
x[(x < 3) | (x > 8)]

[1] 3 4 5 6 7

[1]  1  2  9 10

## 22. `xor()` – exclusive OR

`xor()` is TRUE when exactly one of the two logical inputs is TRUE. It is FALSE when both are TRUE or both are FALSE.

In [ ]:
a <- c(TRUE, TRUE, FALSE, FALSE)
b <- c(TRUE, FALSE, TRUE, FALSE)

xor(a, b)

# Compare ordinary OR and exclusive OR
a | b
xor(a, b)

[1] FALSE  TRUE  TRUE FALSE

[1]  TRUE  TRUE  TRUE FALSE

[1] FALSE  TRUE  TRUE FALSE

## 23. `isTRUE()` and `isFALSE()`

These functions test whether an expression evaluates to the corresponding logical value.

In [ ]:
isTRUE(8 > 6)
isTRUE(8 < 6)

isFALSE(5 > 8)
isFALSE(5 < 8)

# Combined with an expression
x <- 5
isTRUE(2*x > 11)
isTRUE(3*x < 20)

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

## 24. Logical values produced from arithmetic expressions

Arithmetic and relational operators can be combined. The result can then be checked with `is.logical()`.

In [ ]:
x <- 5

Logical4 <- (2*x > 11)
Logical5 <- (3*x < 20)

Logical4
Logical5

is.logical(Logical4)
is.logical(Logical5)

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

## 25. Conceptual mini-problem: classify values using several operators

This combines relational operators, `&`, `|`, `!` and logical indexing in one example.

In [ ]:
scores <- c(35, 48, 55, 67, 74, 89, 92)

# Passing range
pass <- scores >= 50

# Distinction range
distinction <- scores >= 75

# Students who passed but are not in distinction
regular_pass <- pass & !distinction

# Very low OR very high scores
extreme <- (scores < 40) | (scores > 90)

list(
  pass = scores[pass],
  regular_pass = scores[regular_pass],
  extreme = scores[extreme]
)

$pass
[1] 55 67 74 89 92

$regular_pass
[1] 55 67 74

$extreme
[1] 35 92

## 26. Conceptual mini-problem: matrix + logical operators

This combines matrix operations with relational/logical filtering.

In [ ]:
m <- matrix(1:12, nrow = 4, ncol = 3, byrow = TRUE)

m

# Select all matrix elements greater than 4 and less than 10
m[(m > 4) & (m < 10)]

# Select elements that are <= 2 OR >= 11
m[(m <= 2) | (m >= 11)]

# Negate a condition
m[!(m > 4)]

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12

[1] 7 5 8 6 9

[1]  1  2 11 12

[1] 1 4 2 3